In [1]:
#!/usr/bin/env python
import sys
import pandas as pd
import pymongo
import json
import os

In [2]:
#def import_content(filepath):
#    mng_client = pymongo.MongoClient('localhost', 27017)
#    mng_db = mng_client['terror_db'] 
#    collection_name = 'terrorinfo' 
#    db_cm = mng_db[collection_name]
#    cdir = os.path.dirname("Global Terrorism Data")
#    file_res = os.path.join(cdir, filepath)
#
#    data = pd.read_csv(file_res)
#    data_json = json.loads(data.to_json(orient='records'))
#    db_cm.remove()
#    db_cm.insert(data_json)
#
#if __name__ == "__main__":
#  filepath = '/path/to/csv/path'
#  import_content(filepath)

In [3]:
file = 'gtd.csv'
terror_df = pd.read_csv(file, encoding = "ISO-8859-1")


terror_df.head()

C:\Users\mjone\Anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,1.970000e+11,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,1.970000e+11,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,1.970010e+11,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,1.970010e+11,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,1.970010e+11,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [4]:
column_names =list(terror_df)

In [12]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)
# The default port used by MongoDB is 27017
# https://docs.mongodb.com/manual/reference/default-mongodb-port/
db = client.terror_db
collection = db.terrorinfo
for index, row in terror_df.iterrows():
     post = {
        "GTD ID": row['eventid'],
        "Year": row['iyear'],
        "Day": row['iday'],
         "Extended Incident": row['extended'],
         "Extended Incident Resolution": row['resolution'],
         "Incident Summary" :row['summary'],
         "Part of Multiple Incident": row['multiple'],
         "Country ID": row['country'],
         "Country": row['country_txt'],
         "Region": row['region_txt'],
         "City": row['city'],
         "Vicinity": row['vicinity'],
         "Latitude": row['latitude'],
         "Longtitude": row['longitude'],
         "Attack Type 1": row['attacktype1'],
         "Attack Type 1 Information": row['attacktype1_txt'],
         "Attack Type 2": row['attacktype2'],
         "Attack Type 2 Information": row['attacktype2_txt'],
         "Attack Type 3": row['attacktype3'],
         "Attack Type 3 Information": row['attacktype3_txt'],
         "Successful Attack": row['success'],
         "Suicide Attack": row['suicide'],
         "Weapon Type 1": row['weaptype1'],
         "weapon Type 1 Information": row['weaptype1_txt'],
          "Weapon Type2": row['weaptype2'],
         "weapon Type 2 Information": row['weaptype2_txt'],
          "Weapon Type 3 ": row['weaptype3'],
         "weapon Type 3 Information": row['weaptype3_txt'],
          "Weapon Type 4": row['weaptype4'],
         "weapon Type 4 Information": row['weaptype4_txt'],
         "Weapon 1 Subtype": row['weapsubtype1'],
         "Weapon 1 Subtype Information": row['weapsubtype1_txt'],
          "Weapon 2 Subtype": row['weapsubtype2'],
         "Weapon 2 Subtype Information": row['weapsubtype2_txt'],
          "Weapon 3 Subtype": row['weapsubtype3'],
         "Weapon 3 Subtype Information": row['weapsubtype3_txt'],
          "Weapon 4 Subtype": row['weapsubtype4'],
         "Weapon 4 Subtype Information": row['weapsubtype4_txt'],
         "Target 1 Subtype": row ['targsubtype1'],
         "Target 1 Subtype Information": row ['targsubtype1_txt'],
          "Target 2 Subtype": row ['targsubtype2'],
         "Target 2 Subtype Information": row ['targsubtype2_txt'],
          "Target 3 Subtype": row ['targsubtype3'],
         "Target 3 Subtype Information": row ['targsubtype3_txt'],
         "Nationalality of 1 Target Victims": row['natlty1'],
         "Information about Nationalality 1 of Target Victims": row ['natlty1_txt'],
          "Nationalality of 2 Target Victims": row['natlty2'],
         "Information about Nationalality 2 of Target Victims": row ['natlty2_txt'],
          "Nationalality of 3 Target Victims": row['natlty3'],
         "Information about Nationalality 3 of Target Victims": row ['natlty3_txt'],
         "Perpetrator Group Name": row['gname'],
         "Unaffiliated Individual": row['individual'],
         "Number of Perpetrators": row['nperps'],
         "Number of Perpetrators Captured": row['nperpcap'],
         "Competing Claims of Responsibility": row['compclaim'],
         "Motive": row['motive'],
         "Total Fatalities": row['nkill'],
         "Total Perpetrator Fatalities": row['nkillter'],
         "Total Wounded": row['nwound'],
         "Total Perpetrators Wounded": row['nwoundte'],
         "Property Damage": row['property'],
         "Value of Property Damage": row['propvalue'],
         "Hostage or Kidnapping Victims": row['ishostkid'],
         "Total Number of Hostages/ Kidnapping Victims": row['nhostkid'],
         "International- Logistical": row['INT_LOG'],
         "International- Ideological": row['INT_IDEO'],
         "International - Miscellaneous" :row['INT_MISC'],
         "International - Any of the Above": row['INT_ANY']  }  


collection.insert_one(post)

In [13]:
results = collection.find()
for result in results:
    print(result)

{'_id': ObjectId('5ca136c617cc8a2becbcbfa0'), 'GTD ID': 201712000000.0, 'Year': 2017, 'Day': 31, 'Extended Incident': 0, 'Extended Incident Resolution': nan, 'Incident Summary': '12/31/2017: An explosive device was discovered and defused at a plaza in Cotabato City, Maguindanao, Philippines. No group claimed responsibility for the incident.', 'Part of Multiple Incident': 0.0, 'Country ID': 160, 'Country': 'Philippines', 'Region': 'Southeast Asia', 'City': 'Cotabato City', 'Vicinity': 0, 'Latitude': 7.209594, 'Longtitude': 124.24196599999999, 'Attack Type 1': 3, 'Attack Type 1 Information': 'Bombing/Explosion', 'Attack Type 2': nan, 'Attack Type 2 Information': nan, 'Attack Type 3': nan, 'Attack Type 3 Information': nan, 'Successful Attack': 0, 'Suicide Attack': 0, 'Weapon Type 1': 6, 'weapon Type 1 Information': 'Explosives', 'Weapon Type2': nan, 'weapon Type 2 Information': nan, 'Weapon Type 3 ': nan, 'weapon Type 3 Information': nan, 'Weapon Type 4': nan, 'weapon Type 4 Information': nan, 'Weapon 1 Subtype': 16.0, 'Weapon 1 Subtype Information': 'Unknown Explosive Type', 'Weapon 2 Subtype': nan, 'Weapon 2 Subtype Information': nan, 'Weapon 3 Subtype': nan, 'Weapon 3 Subtype Information': nan, 'Weapon 4 Subtype': nan, 'Weapon 4 Subtype Information': nan, 'Target 1 Subtype': nan, 'Target 1 Subtype Information': nan, 'Target 2 Subtype': nan, 'Target 2 Subtype Information': nan, 'Target 3 Subtype': nan, 'Target 3 Subtype Information': nan, 'Nationalality of 1 Target Victims': 160.0, 'Information about Nationalality 1 of Target Victims': 'Philippines', 'Nationalality of 2 Target Victims': nan, 'Information about Nationalality 2 of Target Victims': nan, 'Nationalality of 3 Target Victims': nan, 'Information about Nationalality 3 of Target Victims': nan, 'Perpetrator Group Name': 'Unknown', 'Unaffiliated Individual': 0, 'Number of Perpetrators': -99.0, 'Number of Perpetrators Captured': 0.0, 'Competing Claims of Responsibility': nan, 'Motive': nan, 'Total Fatalities': 0.0, 'Total Perpetrator Fatalities': 0.0, 'Total Wounded': 0.0, 'Total Perpetrators Wounded': 0.0, 'Property Damage': 0, 'Value of Property Damage': nan, 'Hostage or Kidnapping Victims': 0.0, 'Total Number of Hostages/ Kidnapping Victims': nan, 'International- Logistical': -9, 'International- Ideological': -9, 'International - Miscellaneous': 0, 'International - Any of the Above': -9}